# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-10 12:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stargazer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=60)),
                ('avatar_url', models.CharField(max_length=200)),
                ('url', models.CharField(max_length=200)),
                ('html_url', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('comapny', models.CharField(max_length=200)),
                ('blog', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('followers', models.IntegerField(max_length=200)),
                ('following', models.IntegerField(max_length=200)),
            ],
        ),
    ]
