# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-10 17:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gitstar', '0003_auto_20160110_1442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stargazer',
            name='blog',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='stargazer',
            name='company',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='stargazer',
            name='email',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='stargazer',
            name='location',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='stargazer',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
